# AEDecode-Patient1023-RemoteEP.rq
#   Find the Low Level AE terms for patient 01-701-1023 in study CDISCPILOT01. 
# REQ: 1. Endpoint running at 34.216.170.22:5820
#      2. Study data loaded to the graph CTDasRDFOnt  
#         (example instance data from the Ontology)
#      3. Subset of the MedDRA211 as RDF loaded to the graph MedDRA211


PREFIX cdiscpilot01: <https://w3id.org/phuse/cdiscpilot01#>
PREFIX code: <https://w3id.org/phuse/code#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX study: <https://w3id.org/phuse/study#>

SELECT *
WHERE{
    
    SERVICE <http://34.216.170.22:5820/CTDasRDFOnt/query>
    {
        SELECT ?ae ?meddrallt
        WHERE
        {
          cdiscpilot01:Person_01-701-1023  study:afflictedBy ?ae .
          ?ae code:hasCode ?meddrallt .
        }
    }
    SERVICE <http://34.216.170.22:5820/MedDRA211/query>
    {
        SELECT *
        WHERE
        {
            OPTIONAL{
            ?meddrallt skos:prefLabel ?ltLabel 
            }
        }
    }
}
